categories:
  - title: '🚀 Features'
    labels:
      - 'kind/enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
  - title: '🧰 Maintenance'
    labels:
      - 'kind/chore'
      - 'kind/dependencies'
      - 'kind/project'

# Needs to contain all labels from above
include-labels:
  - 'kind/enhancement'
  - 'kind/bug'
  - 'kind/chore'
  - 'kind/dependencies'
  - 'kind/project'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
tag-template: 'v$RESOLVED_VERSION'
name-template: 'v$RESOLVED_VERSION 🌈'
autolabeler:
  - label: 'kind/chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/\[chore\]/i'
  - label: 'kind/dependencies'
    branch:
      - '/dependencies\/.+/'
    title:
      - '/\[dependencies\]/i'
  - label: 'kind/project'
    branch:
      - '/project\/.+/'
    title:
      - '/\[project\]/i'
  - label: 'kind/bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/\[fix\]/i'
  - label: 'kind/enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/\[feature\]/i'
template: |

  # What's Changed

  $CHANGES

  # Usage

  More info can be found in the [installation instructions](https://docs.epinio.io/installation/install_epinio).

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'status/enhancement'
      - 'dependencies'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'status/bug'
      - 'chore'
  default: patch
