---
project_name: epinio-ui

archives:
  - name_template: >-
      {{- .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format: binary
    format_overrides:
      - goos: windows
        format: zip

before:
  hooks:
    - sh -c "cd backend/src/jetstream && go mod download"

release:
  disable: true

dist: /tmp/_dist

# binary builds
builds:

  # amd64
  - id: epinio-ui-amd64
    dir: backend/src/jetstream
    binary: epinio-ui
    ldflags:
      - -w -s -X "main.appVersion={{ incminor .Version }}-next"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++

  # arm64
  - id: epinio-ui-arm64
    dir: backend/src/jetstream
    binary: epinio-ui
    ldflags:
      - -w -s -X "main.appVersion={{ incminor .Version }}-next"
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++

  # s390x
  - id: epinio-ui-s390x
    dir: backend/src/jetstream
    binary: epinio-ui
    ldflags:
      - -w -s -X "main.appVersion={{ incminor .Version }}-next"
    goos:
      - linux
    goarch:
      - s390x
    env:
      - CC=s390x-linux-gnu-gcc
      - CXX=s390x-linux-gnu-g++

changelog:
  skip: false

snapshot:
  name_template: "{{ incminor .Version }}-next"

# docker build
dockers:

  # amd64
  - id: epinio-ui-amd64
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: backend/Dockerfile

    ids:
    - epinio-ui-amd64

    image_templates:
    - "ghcr.io/epinio/epinio-ui:{{ incminor .Version }}-next-amd64"
    - "ghcr.io/epinio/epinio-ui:latest-next-amd64"

    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{ incminor .Version }}-next"
    - "--label=epinio.io.ui.source={{.Env.UI_BUNDLE_URL}}"
    - "--label=org.opencontainers.image.source=https://github.com/epinio/ui"
    - "--build-arg=DIST_BINARY=epinio-ui"
    - "--platform=linux/amd64"

    extra_files:
    - backend/ui/

  # arm64
  - id: epinio-ui-arm64
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: backend/Dockerfile

    ids:
    - epinio-ui-arm64

    image_templates:
    - "ghcr.io/epinio/epinio-ui:{{ incminor .Version }}-next-arm64v8"
    - "ghcr.io/epinio/epinio-ui:latest-next-arm64v8"

    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{ incminor .Version }}-next"
    - "--label=epinio.io.ui.source={{.Env.UI_BUNDLE_URL}}"
    - "--label=org.opencontainers.image.source=https://github.com/epinio/ui"
    - "--build-arg=DIST_BINARY=epinio-ui"
    - "--platform=linux/arm64/v8"

    extra_files:
    - backend/ui/

  # s390x
  - id: epinio-ui-s390x
    goos: linux
    goarch: s390x
    use: buildx
    dockerfile: backend/Dockerfile

    ids:
    - epinio-ui-s390x

    image_templates:
    - "ghcr.io/epinio/epinio-ui:{{ incminor .Version }}-next-s390x"
    - "ghcr.io/epinio/epinio-ui:latest-next-s390x"

    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{ incminor .Version }}-next"
    - "--label=epinio.io.ui.source={{.Env.UI_BUNDLE_URL}}"
    - "--label=org.opencontainers.image.source=https://github.com/epinio/ui"
    - "--build-arg=DIST_BINARY=epinio-ui"
    - "--platform=linux/s390x"

    extra_files:
    - backend/ui/

docker_manifests:
  - id: epinio-ui
    name_template: "ghcr.io/epinio/epinio-ui:latest-next"

    image_templates:
    - ghcr.io/epinio/epinio-ui:{{ incminor .Version }}-next-amd64
    - ghcr.io/epinio/epinio-ui:{{ incminor .Version }}-next-arm64v8
    - ghcr.io/epinio/epinio-ui:{{ incminor .Version }}-next-s390x

# Based on https://blog.goreleaser.com/goreleaser-and-software-supply-chain-security-e8917b26924b
##

# creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
# Two different sbom configurations need two different IDs

sboms:
  - id: archive 
    artifacts: archive
  - id: source
    artifacts: source

# signs our docker images
# https://goreleaser.com/customization/docker_sign

docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    artifacts: all
    output: true
    args:
    - 'sign'
    - '${artifact}'

# signs the checksum file and other blobs. all files (including the sboms) are included in the
# checksum, so we don't need to sign each one if we don't want to
# https://goreleaser.com/customization/sign

signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: checksum
  output: true
