settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: jetstream
  path: .
  commands: 
    run:
      status: true
    install:
      status: false
  watcher:
    extensions:
    - go
    paths:
    - /  
    ignored_paths:
    - .git
    - .realize
    - vendor
