name: Backend - CI

on:
  push:
    branches: [ main ]
    paths:
    - backend/**
    - '!backend/README.md'
  pull_request:
    branches: [ main ]
    paths:
    - backend/**
    - '!backend/README.md'
  # nightly
  # schedule:
  #   - cron:  '0 0 * * *'

defaults:
  run:
    working-directory: ./backend

env:
  SETUP_GO_VERSION: '1.20'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.SETUP_GO_VERSION }}

      - name: Lint
        run: cd src/jetstream && go vet ./...

      - name: Unit Tests
        run: cd src/jetstream && go test -v ./...
